use_frameworks!

platform :ios, '10.0'

target 'SatzHello_Example' do
  pod 'SatzHello', :path => '../'

  target 'SatzHello_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
